add gh-pages publish action to docs workflow
NeuroTechX/EEG-ExPy pull request #62
Opened 2020-12-10 08:01 UTC by jnaulty

Use peaceiris/actions-gh-pages action to publish gh-pages branch

This action comes from a [well-known actions contributor](https://github.blog/2020-03-22-github-action-hero-shohei-ueda/)

More info regarding considerations in choosing this particular
action over other methods:

Github has a great section titled the  [Using third-party actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions)
in their Security Hardening GH Actions documentation.

The gist of this section is basically:
- audit the third-party code
- lock down to a commit (if you're paranoid, or version tag if you're
not too worried)

They have a really important section titled [Considering cross-repository access](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions#considering-cross-repository-access).
Summary of this particular section is is, github recommends the following access methods for
github actions (in order of high recommendation to 'please avoid at all
costs')
-[GITHUB_TOKEN](https://docs.github.com/en/free-pro-team@latest/actions/configuring-and-managing-workflows/authenticating-with-the-github_token)
- repository deploy key
-github app tokens
- personal access tokens
- ssh keys on a user account

2020-12-11 03:42 UTC, JohnGriffiths commented
Dumb question, apols: how does one check that github CI-based code works without merging to master? Can deploy a build from a PR?

2020-12-11 03:49 UTC, JohnGriffiths commented
@jnaulty @ErikBjare if this runs successfully then it seems a very desirable option, as its very simple.

2020-12-11 11:11 UTC, ErikBjare requested changes
A couple of things to get this working.

Looks like the docs workflow isn't running on PRs from other branches. It did before so I can only assume this is due to the use of `GITHUB_TOKEN`. Hopefully the `if:` thing I suggested would let the workflow run anyway (without needing the `GITHUB_TOKEN` to deploy).

2020-12-11 11:11 UTC, ErikBjare commented on .github/workflows/docs.yml
> +	publish_dir: ./html
These tabs should be spaces, to keep things consistent.

And `publish_dir` looks like it's not set correctly.

```suggestion
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: doc/_build/html
```

2020-12-11 11:11 UTC, ErikBjare commented on .github/workflows/docs.yml
> +      uses: peaceiris/actions-gh-pages@v3
Only deploy on master branch.

```suggestion
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
```

2020-12-11 11:29 UTC, ErikBjare approved these changes
Looks good now, merging!

2020-12-11 11:29 UTC, merged

2020-12-18 01:52 UTC, jnaulty commented
Thanks for fixing this up and merging it!
Apologies for the late response, got distracted by other things.